# Generated by Django 4.0.4 on 2022-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_messages_channel', models.IntegerField(null=True)),
                ('data', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='messages_channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sender', models.IntegerField(null=True)),
                ('id_recipient', models.IntegerField(null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
