# Generated by Django 4.0.4 on 2022-06-06 10:52

import django.contrib.postgres.indexes
from django.db import migrations

from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        BtreeGinExtension(),

        migrations.RemoveField(
            model_name='friend_request',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='sender',
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sender', 'receiver', 'message', 'timestamp', 'is_read'], name='chat_messag_sender__298671_gin'),
        ),
        migrations.DeleteModel(
            name='friend_request',
        ),
    ]
